name: Build TV Scanner
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Flipper SDK
        run: |
          sudo apt-get update && sudo apt-get install -y clang cmake protobuf-compiler git
          git clone --recursive https://github.com/flipperdevices/flipperzero-firmware.git
          cd flipperzero-firmware && ./fbt

      - name: Copy Assets
        run: |
          mkdir -p flipperzero-firmware/assets/tv_db
          cp -r assets/tv_db/* flipperzero-firmware/assets/tv_db/

      - name: Compile FAP
        working-directory: ./flipperzero-firmware
        run: |
          ./fap FAP_TV_SCANNER

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tv_scanner.fap
          path: ./flipperzero-firmware/dist/f7-C/fap/tv_scanner.fap
