name: Build TV Scanner
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Clone Flipper Firmware
        run: |
          git clone --recursive --branch dev https://github.com/flipperdevices/flipperzero-firmware.git
          cd flipperzero-firmware
          git submodule update --init --recursive
          mkdir -p applications_user/tv_scanner
          cp -r ../applications/tv_scanner/* applications_user/tv_scanner/
          cp -r ../assets/tv_db assets/

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake protobuf-compiler git python3 python3-pip
          python3 -m pip install python-ulid

      - name: Compile FAP
        working-directory: ./flipperzero-firmware
        run: |
          ./fbt fap_tv_scanner

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tv_scanner.fap
          path: ./flipperzero-firmware/build/f7-firmware-D/.extapps/tv_scanner.fap
